Push: Sun  3 Feb 2019 14:11:15 CET

diff --git a/docker/push b/docker/push
--- a/docker/push
+++ b/docker/push
@@ -1,4 +1,46 @@
 #!/bin/bash -e
+#
+# Push a Docker image to Docker Hub.
 
-# docker push NAME[:TAG]
+################################################################################
+# Configuration
+################################################################################
+# Fail on first error
+set -e
 
+################################################################################
+# Constants
+################################################################################
+
+
+################################################################################
+# Global variables
+################################################################################
+
+
+################################################################################
+# Functions
+################################################################################
+########################################
+# Push a Docker image to Docker Hub.
+#
+# Globals:
+#   None
+# Arguments:
+#   image_name Name of the image.
+#   image_tag Tag of the image.
+# Returns:
+#   None
+########################################
+docker::push() {
+  local image_name="${1}"
+  local image_tag="${2}"
+  echo "docker push \"${image_name}:${image_tag}\""
+  # docker push "${image_name}:${image_tag}"
+}
+
+main() {
+  docker::push "${@}"
+}
+
+main "${@}"
